version: '3'

vars:
  DOCKER_IMAGE: innoviter-site

tasks:
  install:
    desc: Install npm dependencies
    cmds:
      - npm install
    sources:
      - package.json
      - package-lock.json
    generates:
      - node_modules/.package-lock.json

  dev:
    desc: Start Astro dev server (http://localhost:4321)
    deps: [install]
    cmds:
      - npm run dev

  build:
    desc: Build static site to dist/
    deps: [install]
    cmds:
      - npm run build

  preview:
    desc: Preview production build locally (http://localhost:4321)
    deps: [build]
    cmds:
      - npm run preview

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf dist node_modules .astro

  docker:build:
    desc: Build Docker production image
    cmds:
      - docker build -t {{.DOCKER_IMAGE}} .

  docker:dev:
    desc: Start dev server via Docker Compose
    cmds:
      - docker compose --profile dev up

  docker:prod:
    desc: Build and start production container (http://localhost:8080)
    deps: [docker:build]
    cmds:
      - docker compose --profile prod up -d

  docker:stop:
    desc: Stop all Docker Compose services
    cmds:
      - docker compose --profile dev --profile prod down

  lint:
    desc: Run Astro check (type checking)
    deps: [install]
    cmds:
      - npx astro check
